activation: relu
apply_xnor_net: false
batch_size: 50
binarize: true
binarize_input: false
binarize_input_threshold: 0.5
datapath: data
dataset: cifar10
epochs: 500
first_weights_fullprecision: false
gpu_ids:
- '0'
gradient_estimator: bnn
inference: false
l1_fp: false
last_weights_fullprecision: false
layer_order: CPBA
ln_fp: false
loss: CrossEntropy
loss_resolution: 10
lr: 0.001
lr_decay:
- 0.1
- 0.1
- 0.1
- 0.1
lr_milestones:
- 100
- 200
- 300
- 400
model_path: ''
momentum: 0.9
net: VGGNet7
no_batchnorm: false
no_biases: true
no_cuda: false
num_workers: 0
optimizer: adam
regularization: L2
results: results
seed: 3
swish_beta: 10
tern_acts: '00000000'
tern_weights: '000000000'
undeterministic: false
verbose: true
weight_decay: 0
width_infl: 1
width_scale: 1
