# Copyright (c) IDS, RWTH Aachen.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.
#
# Last Modified : Jan. 22, 2024, T. Stadtmann

#####
# This config file contains all necessary parameter to run a experiment
#####
## Usual hyperparameters
epochs : 500
net: VGGNet7
results: 'results'
model_path : ''
inference: False
optimizer : 'sgd'
lr : 0.1
momentum : 0.9
lr_milestones : [80, 120]
lr_decay : [0.1, 0.1]
loss : 'SquareHingeLoss'
regularization : L2
weight_decay : 0.0001
batch_size : 100
num_workers: 0
## Binarization
binarize : False
gradient_estimator : 'vanilla'
swish_beta : 10
layer_order : 'CBAP'
## CNN architecture
no_biases : False
no_batchnorm : False
activation : 'relu'
width_infl : 1
## System and output
no_cuda : False
seed : 1
gpu_ids : ['0']
undeterministic : False
## Dataset
dataset : 'cifar10'
datapath: 'data'
binarize_input : False
binarize_input_threshold : 0.5
## XNOR-Net experiments
apply_xnor_net : False
first_weights_fullprecision : False
last_weights_fullprecision : False
## Capacity experiments
tern_weights : '000000000'
tern_acts : '00000000'
l1_fp : False
ln_fp : False
width_scale : 1
